project_id = "tqbybefpnwxukzqkanip"

[functions.cashout]
verify_jwt = false

[functions.autonomous-agent-swarm]
verify_jwt = false

[functions.stripe-payment-processor]
verify_jwt = false

[functions.financial-failsafe-system]
verify_jwt = false