// This file is automatically generated. Do not edit it directly.
// 
// 🚨 DEPRECATED: Supabase integration is being phased out in favor of Lovable Cloud
// Please use LovableCloudService instead of this Supabase client
//
// Migration guide:
// - Replace supabase.functions.invoke() with LovableCloudService methods
// - Replace supabase.from() queries with LovableCloudService methods
// - Update authentication to use Lovable Cloud auth

import { supabase } from './client-deprecated';

// Show migration warning on first import
if (typeof window !== 'undefined') {
  console.warn(`
🚨 SUPABASE DEPRECATION WARNING 🚨

This application is migrating from Supabase to Lovable Cloud.
The Supabase client you're using is deprecated and will be removed in a future version.

Please migrate to LovableCloudService:
- Import: import { LovableCloudService } from '@/services/LovableCloudService'
- Usage: const lovableCloud = LovableCloudService.getInstance()

For more information, see the migration documentation.
  `);
}

export { supabase };